name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Test NumberProperties
        id: np
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "NumberProperties"
          command: gradle -q test --tests viikko1.NumberPropertiesTest
          timeout: 10
          max-score: 1
      - name: Test SortThree
        id: st
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "SortThree"
          command: gradle -q test --tests viikko1.SortThreeTest
          timeout: 10
          max-score: 1
      - name: Test TimesTable
        id: tt
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "TimesTable"
          command: gradle -q test --tests viikko1.TimesTableTest
          timeout: 10
          max-score: 1
      - name: Test PasswordAttempts
        id: pa
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "PasswordAttempts"
          command: gradle -q test --tests viikko1.PasswordAttemptsTest
          timeout: 10
          max-score: 1
      - name: Test ArrayStats
        id: as
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "ArrayStats"
          command: gradle -q test --tests viikko1.ArrayStatsTest
          timeout: 10
          max-score: 1
      - name: Debug Test Results
        run: |
          echo "${{steps.np.outputs.result}}"
          echo "${{steps.st.outputs.result}}"
          echo "${{steps.tt.outputs.result}}"
          echo "${{steps.pa.outputs.result}}"
          echo "${{steps.as.outputs.result}}"
      - name: Autograding Report
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          NP_RESULTS: "${{steps.np.outputs.result}}"
          ST_RESULTS: "${{steps.st.outputs.result}}"
          TT_RESULTS: "${{steps.tt.outputs.result}}"
          PA_RESULTS: "${{steps.pa.outputs.result}}"
          AS_RESULTS: "${{steps.as.outputs.result}}"
        with:
          runners: np,st,tt,pa,as
